[tool.black]
line-length = 120
target-version = ['py38']
skip-magic-trailing-comma = true

[tool.pylint.messages_control]
max-line-length = 120
[tool.pylint.TYPECHECK]
generated-members = "numpy.*, torch.*"